version: '3.8'
services:
  viridis-signing:
    container_name: viridis-signing
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - viridis-signing
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 